- id: '1522876316388'
  alias: Scene - Turn Off Lights When Watching TV at Night
  trigger:
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      TV"}} '
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      Roku"}} '
  condition:
  - after: '19:00'
    condition: time
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  action:
  - data:
      entity_id: scene.watch_tv
    service: scene.turn_on
  mode: single
- id: '1522888948173'
  alias: Guest Room - Turn on lights with wall switch
  trigger:
  - entity_id: light.guest_room_floor_lamp
    platform: state
    to: 'on'
  action:
  - entity_id: light.office_rgbw
    service: light.turn_on
  - data: {}
    entity_id: light.guest_room_bed_lamp
    service: light.turn_on
  mode: single
- id: '1522889042539'
  alias: Guest Room - Turn off lights with wall switch
  trigger:
  - entity_id: light.guest_room_floor_lamp
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: light.office_rgbw
    service: light.turn_off
  - data: {}
    entity_id: light.guest_room_bed_lamp
    service: light.turn_off
  mode: single
- alias: Home Mode - Set to Home When Anyone Arrives Home and Mode is not Sleep
  id: '1522931077343'
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  - entity_id: person.eric
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Away
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
- alias: Home Mode - Set To Away When Everyone Leaves
  id: '1522931541949'
  trigger:
  - entity_id: group.people
    for: 00:05:00
    platform: state
    to: not_home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Away
    service: input_select.select_option
- alias: Home Mode - Set To Home At Sunrise If Anyone Is Home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
  condition:
  - condition: state
    entity_id: group.people
    state: home
  id: '1522931689561'
  trigger:
  - event: sunrise
    platform: sun
- alias: Home Mode - Set To Sleep At 02:00 If Anyone Is Home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Sleep
    service: input_select.select_option
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  id: '1522931845172'
  trigger:
  - at: 02:00:00
    platform: time
- alias: Kitchen - Unlock Kitchen Door When Someone Arrives Home
  id: '1522931995271'
  trigger:
  - entity_id: person.eric
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  action:
  - data:
      entity_id: lock.kitchen_door_lock_locked
    service: lock.unlock
- alias: Scene - Turn Off Lights And Lock Doors When Everyone Leaves
  action:
  - data:
      entity_id: scene.away
    service: scene.turn_on
  id: '1522945160123'
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Away
- alias: Scene - Turn Off Lights And Lock Doors When Sleep
  action:
  - data:
      entity_id: scene.sleep
    service: scene.turn_on
  id: '1522945234824'
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Sleep
- id: '1522945341172'
  alias: Scene - Turn On Indoor Lights At Dusk
  trigger:
  - entity_id: binary_sensor.dusk
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
  mode: single
- alias: Scene - Turn On Lights When Someone Arrives Home At Dusk or Night
  id: '1523015798070'
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.night
      state: 'on'
    - condition: state
      entity_id: binary_sensor.dusk
      state: 'on'
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
- alias: System - Check for new snapshots daily
  id: '1543376445848'
  trigger:
  - at: 03:00:00
    platform: time
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: rest_command.google_backup
- alias: Switch - Turn on MagicMirror
  id: '1546951741513'
  trigger:
  - at: 06:15:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.mb_magic_mirror_screen
    service: switch.turn_on
- alias: Bedroom - Turn On Main Light With Entry Switch
  id: '1548980303353'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_on
- alias: Bedroom - Turn Off Main Light With Entry Light
  id: '1548980361657'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_off
- alias: Loft - Fan Light Off With Wall Switch
  id: '1573825610778'
  description: Turn of the ceiling fan light with the wall switch. Also set the fan
    to medium speed.
  trigger:
  - entity_id: light.desk_light_switch
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: fan.loft_ceiling_fan
      speed: medium
    service: fan.set_speed
  - data:
      entity_id: light.loft_fan_light
    service: light.turn_off
- alias: System - Weekly Backup
  id: '1573827443988'
  description: Create a weekly backup of HA
  trigger:
  - at: 02:00:00
    platform: time
  condition:
    condition: time
    weekday:
    - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Hassio ({{now().strftime('%d.%m.%y')}})
- alias: Loft - Fan Light Off With Wall Switch
  id: '1577647896286'
  description: ''
  trigger:
  - entity_id: light.desk_light_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.loft_fan_light
    service: light.turn_on
- alias: Fish - Set Fed Time
  id: '1678657997296'
  trigger:
  - platform: state
    entity_id: switch.fish_tank_light
    from: 'off'
    to: 'on'
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.fish_last_fed
      value: '{{states(''sensor.date_time'')}}'
- id: '1577839778680'
  alias: Fish - Send notification when fish need fed
  description: ''
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(strptime(states(''sensor.date_time''), ''%Y-%m-%d,
      %H:%M'')) - as_timestamp(strptime(states(''input_text.fish_last_fed''), ''%Y-%m-%d,
      %H:%M''))|float > 2880 * 60 }}'
  condition: []
  action:
  - data:
      message: Fish have not been fed in two days.
    service: notify.mobile_app_galaxys9
- id: '1578081825952'
  alias: Notification - Notify Eric Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.eric
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_galaxys9
  mode: single
- alias: Notification - Notify Nicole Door Open
  id: '1578081825953'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.nicole
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_pixel_3a
- alias: Scene - Trigger Listen To Music When Input Line1
  id: '1579718011517'
  description: ''
  trigger:
  - platform: template
    value_template: '{{is_state_attr(''media_player.loft_main'', ''source'', ''Line1'')}}'
  condition: []
  action:
  - entity_id: scene.listen_to_music
    service: scene.turn_on
- alias: Notification - Dismiss alert after fish fed
  id: '1579891708175'
  description: ''
  trigger:
  - entity_id: switch.fish_tank_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      notification_id: 49980
    service: persistent_notification.dismiss
- id: '1581713139579'
  alias: Lighting - Outdoor Lights on at Sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.1602368387747
  mode: single
- id: '1581713222232'
  alias: Lighting - Outdoor Lights Off at Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.1602368387748
  mode: single
- id: '1581973044961'
  alias: Switch - Turn Off Humidifiers At Morning
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  - type: turn_off
    device_id: ca0d575e83874565b700fddd31f336c2
    entity_id: switch.office_fan_humidifier_switch
    domain: switch
  mode: single
- id: '1593366918811'
  alias: Notification - Print finished
  description: Send a push notification when the 3D printer goes from on to off.
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Print complete.
    service: notify.mobile_app_pixel_3a
- id: '1600964645726'
  alias: Garage - Turn garage light on with door open
  description: Turn on the garage light when either door to the garage is opened.
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
  - platform: state
    entity_id: binary_sensor.kitchen_garage_door_sensor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.garage_light
    service: light.turn_on
  mode: single
- id: '1601927042547'
  alias: Lighting - Turn off office lights when no motion
  description: When there is no motion in the office for 15 minutes, turn off the
    lights and pause music.
  trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_sensor
    from: 'on'
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: light.guest_room_floor_lamp
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.office_rgbw
  - service: light.turn_off
    data: {}
    entity_id: light.guest_room_bed_lamp
  - service: light.turn_off
    data: {}
    entity_id: light.guest_room_floor_lamp
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.office_music_squeezelite
  mode: single
- id: '1602094793399'
  alias: Office - Turn fan/humidifier off when I wake up
  description: Look for motion between 6:30-9:30, and turn off fan when it's detected.
  trigger:
  - platform: state
    entity_id: binary_sensor.home_office_door_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '6:30'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: '7:30'
  - condition: time
    weekday:
    - sat
    - sun
    after: '8:00'
    before: '10:00'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.office_fan_humidifier_switch
  mode: single
- id: '1602610938827'
  alias: Bedroom - Turn off humidifier when everyone wakes up
  description: When the bedroom door is opened between 6:00 and 13:00, and no phones
    are charging, turn off the humidifier.
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_door_sensor
    from: 'off'
    to: 'on'
  condition:
  - type: is_not_plugged_in
    condition: device
    device_id: c05f4c9d3c894cb7aa86080865fa4c08
    entity_id: binary_sensor.galaxys9_is_charging
    domain: binary_sensor
  - type: is_not_plugged_in
    condition: device
    device_id: e6c6a573bc544ba7b3f030f34c4b40d3
    entity_id: binary_sensor.pixel_3a_is_charging
    domain: binary_sensor
  - condition: time
    after: '6:00'
    before: '13:00'
  action:
  - type: turn_off
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  mode: single
