- id: '1522876316388'
  alias: Scene - Turn Off Lights When Watching TV at Night
  trigger:
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      TV"}} '
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      Roku"}} '
  condition:
  - after: '19:00'
    condition: time
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  action:
  - data:
      entity_id: scene.watch_tv
    service: scene.turn_on
  mode: single
- id: '1522931077343'
  alias: Home Mode - Set to Home When Anyone Arrives Home and Mode is not Sleep
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  - entity_id: person.eric
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Away
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
  mode: restart
- alias: Home Mode - Set To Away When Everyone Leaves
  id: '1522931541949'
  trigger:
  - entity_id: group.people
    for: 00:05:00
    platform: state
    to: not_home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Away
    service: input_select.select_option
- id: '1522931689561'
  alias: Home Mode - Set To Home 30 minutes before blinds open
  description: When anyone is home, set the home mode to Home 30 minutes before the
    blinds are set to open.
  trigger:
  - platform: time
    at: input_datetime.open_blinds_time
  - platform: template
    value_template: '{% set hour_before_wake = (state_attr(''input_datetime.open_blinds_time'',
      ''hour'') - 1) %} {{now().hour == hour_before_wake}}'
  - platform: sun
    event: sunrise
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
  mode: single
- alias: Home Mode - Set To Sleep At 02:00 If Anyone Is Home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Sleep
    service: input_select.select_option
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  id: '1522931845172'
  trigger:
  - at: 02:00:00
    platform: time
- alias: Kitchen - Unlock Kitchen Door When Someone Arrives Home
  id: '1522931995271'
  trigger:
  - entity_id: person.eric
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  action:
  - data:
      entity_id: lock.kitchen_door_lock_locked
    service: lock.unlock
- alias: Scene - Turn Off Lights And Lock Doors When Everyone Leaves
  action:
  - data:
      entity_id: scene.away
    service: scene.turn_on
  id: '1522945160123'
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Away
- id: '1522945234824'
  alias: Scene - Turn Off Lights And Lock Doors When Sleep
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Sleep
  action:
  - data:
      entity_id: scene.sleep
    service: scene.turn_on
  mode: single
- id: '1522945341172'
  alias: Scene - Turn On Indoor Lights At Dusk
  trigger:
  - entity_id: binary_sensor.dusk
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
  mode: single
- id: '1523015798070'
  alias: Scene - Turn On Lights When Someone Arrives Home At Dusk or Night
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.night
      state: 'on'
    - condition: state
      entity_id: binary_sensor.dusk
      state: 'on'
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
  mode: single
- alias: System - Check for new snapshots daily
  id: '1543376445848'
  trigger:
  - at: 03:00:00
    platform: time
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: rest_command.google_backup
- alias: Bedroom - Turn On Main Light With Entry Switch
  id: '1548980303353'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_on
- alias: Bedroom - Turn Off Main Light With Entry Light
  id: '1548980361657'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_off
- alias: System - Weekly Backup
  id: '1573827443988'
  description: Create a weekly backup of HA
  trigger:
  - at: 02:00:00
    platform: time
  condition:
    condition: time
    weekday:
    - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Hassio ({{now().strftime('%d.%m.%y')}})
- alias: Fish - Set Fed Time
  id: '1678657997296'
  trigger:
  - platform: state
    entity_id: switch.fish_tank_light
    from: 'off'
    to: 'on'
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.fish_last_fed
      value: '{{states(''sensor.date_time'')}}'
- id: '1577839778680'
  alias: Fish - Send notification when fish need fed
  description: ''
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(strptime(states(''sensor.date_time''), ''%Y-%m-%d,
      %H:%M'')) - as_timestamp(strptime(states(''input_text.fish_last_fed''), ''%Y-%m-%d,
      %H:%M''))|float > 2880 * 60 }}'
  condition: []
  action:
  - data:
      message: Fish have not been fed in two days.
    service: notify.mobile_app_erics_iphone
  mode: single
- id: '1578081825952'
  alias: Notification - Notify Eric Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.eric
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_erics_iphone
  mode: single
- alias: Notification - Notify Nicole Door Open
  id: '1578081825953'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.nicole
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_pixel_3a
- alias: Notification - Dismiss alert after fish fed
  id: '1579891708175'
  description: ''
  trigger:
  - entity_id: switch.fish_tank_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      notification_id: 49980
    service: persistent_notification.dismiss
- id: '1581713139579'
  alias: Lighting - Outdoor Lights on at Sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.1602368387747
  mode: single
- id: '1581713222232'
  alias: Lighting - Outdoor Lights Off at Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.1602368387748
  mode: single
- id: '1581973044961'
  alias: Switch - Turn On Humidifiers At Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  - type: turn_on
    device_id: ca0d575e83874565b700fddd31f336c2
    entity_id: switch.office_fan_humidifier_switch
    domain: switch
  mode: single
- id: '1593366918811'
  alias: Notification - Print finished
  description: Send a push notification when the 3D printer goes from on to off.
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Print complete.
    service: notify.mobile_app_pixel_3a
- id: '1600964645726'
  alias: Garage - Turn garage light on with door open
  description: Turn on the garage light when either door to the garage is opened.
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: opening
    attribute: door_state
  - platform: state
    entity_id: binary_sensor.kitchen_garage_door_sensor
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.garage_light
    service: light.turn_on
  mode: single
- id: '1601927042547'
  alias: Office - Turn off office lights when no motion
  description: When there is no motion in the office for 15 minutes, turn off the
    lights.
  trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_sensor
    from: 'on'
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: binary_sensor.home_office_door_sensor
    state: 'on'
  action:
  - type: turn_off
    device_id: e93c31a0056d8f643306aa69147fd759
    entity_id: light.office_bed_light
    domain: light
  - service: light.turn_off
    data: {}
    entity_id: light.guest_room_floor_lamp
  - type: turn_off
    device_id: 4aac034661657e0e02201862965efd4d
    entity_id: light.office_rgbw
    domain: light
  mode: single
- id: '1603114369121'
  alias: Notify - Check if GFI Tripped
  description: If the Shield tablet isn't plugged in, it's likely because the GFI
    has tripped. Notify on that condition.
  trigger:
  - type: not_plugged_in
    platform: device
    device_id: a79348a9f549481a999840a336e6d7b0
    entity_id: binary_sensor.shield_tablet_k1_is_charging
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_pixel_3a
    data:
      message: Check if GFI tripped.
  - service: notify.mobile_app_erics_iphone
    data:
      message: Check if GFI tripped.
  mode: single
- id: '1603310291699'
  alias: Is it time to open the blinds?
  description: ''
  trigger:
  - platform: time
    at: input_datetime.open_blinds_time
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.time_to_open_blinds
  mode: single
- id: '1605414468654'
  alias: Notification - Motion detected on porch
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 7d8f11cc13f111eba8a2950e966cf104
    entity_id: binary_sensor.blueiris_porch_camera_motion
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_pixel_3a
    data:
      message: Motion detected on porch.
  - service: notify.mobile_app_erics_iphone
    data:
      message: Motion detected on porch.
  mode: single
- id: '1605810437212'
  alias: Good Morning Bedroom
  description: When the blinds open, turn on the plant lights and magic mirror. Turn
    off the Bedroom Humidifier.
  trigger:
  - platform: state
    entity_id: input_boolean.time_to_open_blinds
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.plant_light
      - switch.mb_magic_mirror_screen
      - switch.seed_start_light
  - type: turn_on
    device_id: 49fab7540e6fe1f69ed4e3dfac928396
    entity_id: switch.hall_plant_lights
    domain: switch
  - type: turn_off
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  mode: single
- id: '1605810525519'
  alias: Turn Off Plant Light At Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.plant_light
      - switch.seed_start_light
  - type: turn_off
    device_id: 49fab7540e6fe1f69ed4e3dfac928396
    entity_id: switch.hall_plant_lights
    domain: switch
  mode: single
- id: '1606675903251'
  alias: Tag Listen To Music is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: f7889a1c-a431-49da-93db-b38ef3d03cf4
  condition: []
  action:
  - scene: scene.listen_to_music
  mode: single
- id: '1606676237934'
  alias: Tag Read is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 99749d42-158d-4e32-aa3e-a5a2d08177bf
  condition: []
  action:
  - scene: scene.read
  mode: single
- id: '1606676307650'
  alias: Tag Work is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: ddafd438-5814-4669-ae60-4852d653482d
  condition: []
  action:
  - scene: scene.work
  mode: single
- id: '1606676456455'
  alias: Tag Goodnight Office is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: d9299984-99ae-49b1-8744-2ae89f5db8d5
  condition: []
  action:
  - scene: scene.goodnight_office
  mode: single
- id: '1606677028890'
  alias: Tag Goodnight Bedroom - Nicole Nightstand is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 888ae6de-fec0-44ba-9c96-97ca9c8c55f9
  condition: []
  action:
  - scene: scene.bedroom_lights_off
  mode: single
- id: '1606677313814'
  alias: Tag Goodnight - Eric Nightstand is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: fbd1479a-a4eb-402d-8bfa-d8a10db2341c
  condition: []
  action:
  - scene: scene.sleep
  mode: single
- id: '1606677325949'
  alias: Tag Goodnight - Nicole Nightstand is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: d08bfa6b-d279-4aa8-8fe1-5d7d46d1e098
  condition: []
  action:
  - scene: scene.sleep
  mode: single
- id: '1606677698755'
  alias: Tag Goodnight Bedroom - Eric Nightstand is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: b803ac20-0e21-448e-ac03-a0c2bc60f1b7
  condition: []
  action:
  - scene: scene.bedroom_lights_off
  mode: single
- id: '1606678221092'
  alias: Lighting - Dim lights when Eric coming home from nightshift
  description: ''
  trigger:
  - platform: state
    entity_id: person.eric
    from: BCC
  condition:
  - condition: time
    after: 04:00
    before: 06:00
  action:
  - scene: scene.dim_bedroom
  mode: single
- id: '1606852374881'
  alias: Office Humidity
  description: When the heat is on, and the office is below 50% humidity, turn on
    the humidifier.
  trigger:
  - type: value
    platform: device
    device_id: d5012fca05d911ebabf433de95c43c23
    entity_id: sensor.office_multi_sensor_relative_humidity
    domain: sensor
    below: 45
  condition:
  - condition: device
    device_id: 715ef382de38445b91848aee1c3edcae
    domain: climate
    entity_id: climate.living_room
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - type: turn_on
    device_id: ca0d575e83874565b700fddd31f336c2
    entity_id: switch.office_fan_humidifier_switch
    domain: switch
  mode: single
- id: '1608135961867'
  alias: Nicole - Office Wakeup
  description: Use RBG as wakeup light based on alarm on my phone.
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      min_mired: '0'
      light_entity: light.office_rgbw
      timestamp_sensor: sensor.pixel_3a_next_alarm
      manual_time: '9:00:00'
      sunrise_duration: 30
      pre_sunrise_actions:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: Home
        entity_id: input_select.home_mode
      - type: turn_off
        device_id: ca0d575e83874565b700fddd31f336c2
        entity_id: switch.office_fan_humidifier_switch
        domain: switch
      end_brightness: '254'
      start_brightness: '1'
