- alias: Scene - Turn Off Lights When Watching TV at Night
  id: '1522876316388'
  trigger:
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      TV"}} '
  - platform: template
    value_template: '{{states.remote.living_room.attributes.current_activity == "Watch
      Roku"}} '
  condition:
  - after: '19:29'
    condition: time
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  action:
  - data:
      entity_id: scene.watch_tv
    service: scene.turn_on
- id: '1522888948173'
  alias: Guest Room - Turn on lights with wall switch
  trigger:
  - entity_id: light.guest_room_floor_lamp
    platform: state
    to: 'on'
  action:
  - entity_id: light.office_rgbw
    service: light.turn_on
  - data: {}
    entity_id: light.guest_room_bed_lamp
    service: light.turn_on
  mode: single
- id: '1522889042539'
  alias: Guest Room - Turn off lights with wall switch
  trigger:
  - entity_id: light.guest_room_floor_lamp
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: light.office_rgbw
    service: light.turn_off
  - data: {}
    entity_id: light.guest_room_bed_lamp
    service: light.turn_off
  mode: single
- alias: Home Mode - Set to Home When Anyone Arrives Home and Mode is not Sleep
  id: '1522931077343'
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  - entity_id: person.eric
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Away
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
- alias: Home Mode - Set To Away When Everyone Leaves
  id: '1522931541949'
  trigger:
  - entity_id: group.people
    for: 00:05:00
    platform: state
    to: not_home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Away
    service: input_select.select_option
- alias: Home Mode - Set To Home At Sunrise If Anyone Is Home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Home
    service: input_select.select_option
  condition:
  - condition: state
    entity_id: group.people
    state: home
  id: '1522931689561'
  trigger:
  - event: sunrise
    platform: sun
- alias: Home Mode - Set To Sleep At 02:00 If Anyone Is Home
  action:
  - data:
      entity_id: input_select.home_mode
      option: Sleep
    service: input_select.select_option
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  id: '1522931845172'
  trigger:
  - at: 02:00:00
    platform: time
- alias: Kitchen - Unlock Kitchen Door When Someone Arrives Home
  id: '1522931995271'
  trigger:
  - entity_id: person.eric
    platform: state
    to: home
  - entity_id: person.nicole
    platform: state
    to: home
  action:
  - data:
      entity_id: lock.kitchen_door_lock_locked
    service: lock.unlock
- alias: Scene - Turn Off Lights And Lock Doors When Everyone Leaves
  action:
  - data:
      entity_id: scene.away
    service: scene.turn_on
  id: '1522945160123'
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Away
- alias: Scene - Turn Off Lights And Lock Doors When Sleep
  action:
  - data:
      entity_id: scene.sleep
    service: scene.turn_on
  id: '1522945234824'
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: Sleep
- id: '1522945341172'
  alias: Scene - Turn On Indoor Lights At Dusk
  trigger:
  - entity_id: binary_sensor.dusk
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  - condition: and
    conditions:
    - condition: state
      entity_id: remote.living_room
      state: 'off'
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
- alias: Scene - Turn On Lights When Someone Arrives Home At Dusk or Night
  id: '1523015798070'
  trigger:
  - entity_id: group.people
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.night
      state: 'on'
    - condition: state
      entity_id: binary_sensor.dusk
      state: 'on'
  action:
  - data:
      entity_id: scene.indoor_lights_on
    service: scene.turn_on
- alias: System - Check for new snapshots daily
  id: '1543376445848'
  trigger:
  - at: 03:00:00
    platform: time
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: rest_command.google_backup
- alias: Switch - Turn on MagicMirror
  id: '1546951741513'
  trigger:
  - at: 06:15:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.mb_magic_mirror_screen
    service: switch.turn_on
- alias: Bedroom - Turn On Main Light With Entry Switch
  id: '1548980303353'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_on
- alias: Bedroom - Turn Off Main Light With Entry Light
  id: '1548980361657'
  trigger:
  - entity_id: light.bedroom_entry_light
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.bedroom_light_switch
    service: light.turn_off
- id: '1649208103764'
  alias: Switch - Turn on Humidifiers at Night
  trigger:
  - entity_id: binary_sensor.night
    platform: state
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  - type: turn_on
    device_id: ca0d575e83874565b700fddd31f336c2
    entity_id: switch.office_fan_humidifier_switch
    domain: switch
  mode: single
- alias: Loft - Fan Light Off With Wall Switch
  id: '1573825610778'
  description: Turn of the ceiling fan light with the wall switch. Also set the fan
    to medium speed.
  trigger:
  - entity_id: light.desk_light_switch
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: fan.loft_ceiling_fan
      speed: medium
    service: fan.set_speed
  - data:
      entity_id: light.loft_fan_light
    service: light.turn_off
- alias: System - Weekly Backup
  id: '1573827443988'
  description: Create a weekly backup of HA
  trigger:
  - at: 02:00:00
    platform: time
  condition:
    condition: time
    weekday:
    - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Hassio ({{now().strftime('%d.%m.%y')}})
- alias: Loft - Fan Light Off With Wall Switch
  id: '1577647896286'
  description: ''
  trigger:
  - entity_id: light.desk_light_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.loft_fan_light
    service: light.turn_on
- alias: Fish - Set Fed Time
  id: '1678657997296'
  trigger:
  - platform: state
    entity_id: switch.fish_tank_light
    from: 'off'
    to: 'on'
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.fish_last_fed
      value: '{{states(''sensor.date_time'')}}'
- id: '1577839778680'
  alias: Fish - Send notification when fish need fed
  description: ''
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(strptime(states(''sensor.date_time''), ''%Y-%m-%d,
      %H:%M'')) - as_timestamp(strptime(states(''input_text.fish_last_fed''), ''%Y-%m-%d,
      %H:%M''))|float > 2880 * 60 }}'
  condition: []
  action:
  - data:
      message: Fish have not been fed in two days.
    service: notify.mobile_app_galaxys9
- alias: Notification - Notify Eric Door Open
  id: '1578081825952'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.eric
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_sm_g965u
- alias: Notification - Notify Nicole Door Open
  id: '1578081825953'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_patio_door_motion_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_door_sensor
    for: 00:00:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.nicole
    state: home
  action:
  - data:
      message: Door left open.
    service: notify.mobile_app_pixel_3a
- alias: Scene - Trigger Listen To Music When Input Line1
  id: '1579718011517'
  description: ''
  trigger:
  - platform: template
    value_template: '{{is_state_attr(''media_player.loft_main'', ''source'', ''Line1'')}}'
  condition: []
  action:
  - entity_id: scene.listen_to_music
    service: scene.turn_on
- alias: Notification - Dismiss alert after fish fed
  id: '1579891708175'
  description: ''
  trigger:
  - entity_id: switch.fish_tank_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      notification_id: 49980
    service: persistent_notification.dismiss
- alias: Mailbox - Reset mailboxPIR state
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.mailbox
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/RFBridge/RESULT
      payload: 9B1620off
  id: 423ae9691e5c4140bdc9547fd69a1fed
- alias: MBCloset - Reset MBClosetPIR state
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.closet_pir
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/RFBridge/RESULT
      payload: 121619off
  id: 25648f5637ba4a03987fdd9f25b869cc
- alias: MBCloset - turn light on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.closet_pir
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bedroom_closet_light_switch
  id: 6ab4458fae84471fb66e9a597822f799
- alias: MBCloset - turn light off
  id: '1681203496897'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.bedroom_closet_light_switch
    from: 'off'
    to: 'on'
    for:
      minutes: 15
  action:
  - service: light.turn_off
    entity_id: light.bedroom_closet_light_switch
- alias: Garage 1 - Reset garagePIR state
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_pir_1
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/RFBridge/RESULT
      payload: F22A20off
  id: 47cbe31aece64b6c86bca7c3a38591a1
- alias: Garage 2 - Reset garagePIR state
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_pir_2
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  action:
  - service: mqtt.publish
    data:
      topic: tele/RFBridge/RESULT
      payload: 937860off
  id: 5aced3b758174fc3a83cd7ae80bd91ef
- alias: Garage1 - turn light on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_pir_1
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.garage_light
  id: 075b8a30da8b46c09874aadb0ef78ded
- alias: Garage2 - turn light on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_pir_2
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.garage_light
  id: e00b831d6fc54f85b2fa056bbdae8941
- id: debe92329291497898094bf0c5b9f084
  alias: Garage - turn light off
  trigger:
  - entity_id: light.garage_light
    for: 0:30:00
    platform: state
    to: 'on'
  action:
  - entity_id: light.garage_light
    service: light.turn_off
  initial_state: 'on'
  mode: single
- id: '1782213597807'
  alias: Notification - Mailbox Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.mailbox
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Mailbox has been opened.
    service: notify.mobile_app_pixel_3a
  - data:
      message: Mailbox has been opened.
    service: notify.mobile_app_galaxys9
- alias: Lighting - Outdoor Lights on at Sunset
  id: '1581713139579'
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: light.outdoor_lights
    service: light.turn_on
- alias: Lighting - Outdoor Lights Off at Sunrise
  id: '1581713222232'
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: light.outdoor_lights
    service: light.turn_off
- id: '1581973044961'
  alias: Switch - Turn Off Humidifiers At Morning
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: 77972d09c4204f5095233e8d46f78bb6
    entity_id: switch.bedroom_humidifier
    domain: switch
  - type: turn_off
    device_id: ca0d575e83874565b700fddd31f336c2
    entity_id: switch.office_fan_humidifier_switch
    domain: switch
  mode: single
- id: '1593366918811'
  alias: Notification - Print finished
  description: Send a push notification when the 3D printer goes from on to off.
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Print complete.
    service: notify.mobile_app_pixel_3a
- id: '1600964645726'
  alias: Lighting - Turn garage light on with door open
  description: ''
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
  condition: []
  action:
  - data: {}
    entity_id: light.garage_light
    service: light.turn_on
  mode: single
- id: '1601927042547'
  alias: Lighting - Turn off office lights when no motion
  description: When there is no motion in the office for 15 minutes, turn off the
    lights and pause music.
  trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_sensor
    from: 'on'
    to: 'off'
    for: 0:15:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.office_rgbw
  - service: light.turn_off
    data: {}
    entity_id: light.guest_room_bed_lamp
  - service: light.turn_off
    data: {}
    entity_id: light.guest_room_floor_lamp
  - service: media_player.media_pause
    data: {}
    entity_id: media_player.office_music_squeezelite
  mode: single
