################
# MQTT Sensors #
################
# rf bridge PIR
- platform: mqtt
  state_topic: "tele/RFBridge/RESULT"
  name: 'Mailbox'
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: '9B1620'
  payload_off: '9B1620off'
  device_class: motion
  qos: 1
  unique_id: mailbox_pir_sensor
- platform: mqtt
  state_topic: "tele/RFBridge/RESULT"
  name: 'Garage PIR 1'
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: 'F22A20'
  payload_off: 'F22A20off'
  device_class: motion
  qos: 1
  unique_id: garage_pir_sensor_1
- platform: mqtt
  state_topic: "tele/RFBridge/RESULT"
  name: 'Garage PIR 2'
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: '937860'
  payload_off: '937860off'
  device_class: motion
  qos: 1
  unique_id: garage_pir_sensor_2
  
####################
# Snow Tire Sensor #
####################
- platform: snowtire
  weather: weather.openweathermap

####################
# Template Sensors #
####################
- platform: template
  sensors: 
    # Doors
    living_room_door_sensor:
      friendly_name: "Living Room Door"
      device_class: door
      value_template: "{{ is_state('sensor.living_room_door_sensor_access_control', '22') }}"
      unique_id: living_room_door_sensor_id
    kitchen_patio_door_motion_sensor:
      friendly_name: "Kitchen Patio Door"
      device_class: door
      value_template: "{{ is_state('sensor.kitchen_patio_door_motion_alarm_level', '255') }}"
      unique_id: kitchen_patio_door_motion_sensor_id
    home_office_door_sensor:
      friendly_name: "Office Door"
      device_class: door
      value_template: "{{ is_state('sensor.home_office_door_sensor_access_control', '22') }}"
      unique_id: home_office_door_sensor_id
    kitchen_garage_door_sensor:
      friendly_name: "Kitchen Garage Door"
      device_class: door
      value_template: "{{ is_state('sensor.kitchen_garage_door_access_control', '22') }}"
      unique_id: kitchen_garage_door_sensor_id
    bedroom_door_sensor:
      friendly_name: "Bedroom Door"
      device_class: door
      value_template: "{{ is_state('sensor.bedroom_door_access_control', '22') }}"
      unique_id: bedroom_door_sensor_id
    # Motion
    office_motion_sensor:
      friendly_name: "Office Multi Sensor"
      device_class: motion
      unique_id: 15902office
      value_template: "{{ is_state('sensor.office_multi_sensor_burglar', '8') }}"
    

######################
# Time of Day Sensor #
######################
- platform: tod
  name: Morning
  before: sunrise
  after: 06:00:00
  before_offset: '2:00:00'
- platform: tod
  name: Day
  after: sunrise
  after_offset: '2:00:00'
  before: sunset
  before_offset: '-1:00:00'
- platform: tod
  name: Dusk
  after: sunset
  after_offset: '-1:00:00'
  before: sunset
- platform: tod
  name: Night
  after: sunset
  before: sunrise