#####################
# Basic Information #
#####################
homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_networks
hassio:

##############
# Automation #
##############
alert: !include alerts.yaml
automation: !include automations.yaml
input_boolean:
input_select:
input_text:
input_number:
input_datetime:
rest_command:
  google_backup:
    url: !secret google_backup_url
    timeout: '300'
script: !include scripts.yaml
timer: !include timers.yaml
python_script:

############
# Calendar #
############
google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret
remember_the_milk:
  - name: nicole_rtm
    api_key: !secret rtm_api
    shared_secret: !secret rtm_secret

##########
# Camera #
##########
camera: !include cameras.yaml
#stream:

#########
# Cover #
#########
cover: !include cover.yaml

########
# HACS #
########
config:
frontend:
  themes: !include_dir_merge_named themes

##########
# Health #
##########
iqvia:
  zip_code: !secret pollen_zip_code
  
######################
# History Components #
######################
history: !include history.yaml
influxdb:
  host: localhost
  port: 8086
  database: !secret influx_db
  username: !secret  influx_un
  password: !secret http_password
  default_measurement: state
logbook:
recorder: !include recorder.yaml

#######
# Hub #
#######
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
octoprint:
  host: !secret OctoIP
  api_key: !secret OctoAPI
  bed: true
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret network_key
  polling_interval: 30000
  device_config: !include zwave_device_config.yaml


################
# Media Player #
################
media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.205
    port: 5005
  - platform: yamaha_musiccast
    host: 192.168.1.81
    port: 5004
  - platform: hifiberry
    host: 192.168.1.224

##############
# Irrigation #
##############
rachio:
  api_key: !secret rachio_api_key

################
# Organization #
################
group: !include groups.yaml
scene: !include scenes.yaml

#########
# Other #
#########
api:
http:
mobile_app:
system_health:

#################
# Notifications #
#################
notify:
  - platform: html5 
    name: chrome_push_notification
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret nicole_email

###########
# Network #
###########
ssdp:
zeroconf:

######################
# Presence Detection #
######################
map:
person:

##########
# Remote #
##########
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.20.6

###########
# Sensor #
###########
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

###########
# Switch  #
###########
fan: !include fans.yaml
switch: !include switches.yaml
light: !include lights.yaml

#####################
# System Monitoring #
#####################
fastdotcom:
  scan_interval:
    minutes: 60
speedtestdotnet:
  scan_interval:
    minutes: 65
  monitored_conditions:
    - ping
    - download
    - upload

###########
# Utility #
###########
logger:
  default: warning
  logs: 
    homeassistant.components.octoprint: fatal
    pysqueezebox.server: fatal


######################
# Weather Components #
######################
sun:
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily