########
# MQTT #
########
# Exahust Fan
- platform: mqtt
  name: "Bedroom Exhaust Fan"
  state_topic: "stat/MB_Exhaust_Fan/POWER"
  command_topic: "cmnd/MB_Exhaust_Fan/POWER"
  availability_topic: "tele/MB_Exhaust_Fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: 68c63ae4493b