########
# MQTT #
########
# Exahust Fan
- platform: mqtt
  name: "Bedroom Exhaust Fan"
  state_topic: "stat/MB_Exhaust_Fan/POWER"
  command_topic: "cmnd/MB_Exhaust_Fan/POWER"
  availability_topic: "tele/MB_Exhaust_Fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: 68c63ae4493b
# Loft Fan
- platform: mqtt
  name: "Loft Ceiling Fan"
  command_topic: "cmnd/LoftFan/FanSpeed"
  speed_command_topic: "cmnd/LoftFan/FanSpeed"
  state_topic: "stat/LoftFan/RESULT"
  speed_state_topic: "stat/LoftFan/RESULT"
  state_value_template: >
    {% if value_json.FanSpeed is defined %}
      {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
    {% else %}
      {% if states.fan.loft_ceiling_fan.state == 'off' -%}0{%- elif states.fan.loft_ceiling_fan.state == 'on' -%}4{%- endif %}
    {% endif %}
  speed_value_template: "{{ value_json.FanSpeed }}"
  availability_topic: tele/LoftFan/LWT
  payload_off: "0"
  payload_on: "4"
  payload_low_speed: "1"
  payload_medium_speed: "2"
  payload_high_speed: "3"
  payload_available: Online
  payload_not_available: Offline
  speeds:
    - low
    - medium
    - high
  unique_id: dc4f22b06033
