#########
# Group #
#########
- platform: group
  name: Outdoor Lights
  entities:
    - light.deck_flood_lights
    - light.flood_light_1
    - light.flood_light_2
    - light.flood_light_3
    - light.garage_flood_lights
    - light.landscaping_lights
    - light.patio_flood_lights
    - light.pier_lights
    - light.pond_light
    - light.porch_light
    - light.workshop_light
- platform: group
  name: Holiday Lights
  entities:
    - light.outdoor_string_lights
    - light.wled1_outsidelow
    - light.wled1_outsidelow_2
    - light.wled2_outsidegara
    - light.wled2_outsidegara_2
    - light.wled3_outsideeyebrow
    - light.wled3_outsideeyebrow_2
- platform: group
  name: Bedroom Lights
  entities:
    - light.bathroom_mirror_led
    - light.bathroom_shower
    - light.bathroom_vanity_light
    - light.bedroom_closet_light_switch
    - light.bedroom_entry_light
    - light.bedroom_light_switch
- platform: group
  name: Living Room Lights
  entities:
    - light.bar_lights
    - light.fireplace_lights
    - light.globe_lamp
    - light.table_lamps

########
# MQTT #
########
# Shower
- platform: mqtt
  name: "Bathroom Shower"
  state_topic: "stat/MB_Shower_light/POWER"
  command_topic: "cmnd/MB_Shower_light/POWER"
  availability_topic: "tele/MB_Shower_light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Bedroom Lights
- platform: mqtt
  name: "Bedroom Light Switch"
  state_topic: "stat/BedroomDimmer/POWER"
  command_topic: "cmnd/BedroomDimmer/POWER"
  availability_topic: "tele/BedroomDimmer/LWT"
  brightness_state_topic: "stat/BedroomDimmer/RESULT"
  brightness_command_topic: "cmnd/BedroomDimmer/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Bedroom Entry Light"
  state_topic: "stat/BedroomEntry/POWER"
  command_topic: "cmnd/BedroomEntry/POWER"
  availability_topic: "tele/BedroomEntry/LWT"
  brightness_state_topic: "stat/BedroomEntry/RESULT"
  brightness_command_topic: "cmnd/BedroomEntry/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Bathroom Vanity Light"
  state_topic: "stat/BathroomVanity/POWER"
  command_topic: "cmnd/BathroomVanity/POWER"
  availability_topic: "tele/BathroomVanity/LWT"
  brightness_state_topic: "stat/BathroomVanity/RESULT"
  brightness_command_topic: "cmnd/BathroomVanity/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Bedroom Closet Light Switch"
  state_topic: "stat/MB_closetlight_shelly/POWER"
  command_topic: "cmnd/MB_closetlight_shelly/POWER"
  availability_topic: "tele/MB_closetlight_shelly/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Dining Room Lights
- platform: mqtt
  name: "Dining Room Light"
  state_topic: "stat/DiningRoom/POWER"
  command_topic: "cmnd/DiningRoom/POWER"
  availability_topic: "tele/DiningRoom/LWT"
  brightness_state_topic: "stat/DiningRoom/RESULT"
  brightness_command_topic: "cmnd/DiningRoom/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Gym Lights
- platform: mqtt
  name: "Gym Light Switch"
  state_topic: "stat/GymLight/POWER"
  command_topic: "cmnd/GymLight/POWER"
  availability_topic: "tele/GymLight/LWT"
  brightness_state_topic: "stat/GymLight/RESULT"
  brightness_command_topic: "cmnd/GymLight/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Loft Lights
- platform: mqtt
  name: "Desk Light Switch"
  state_topic: "stat/DeskLight/POWER"
  command_topic: "cmnd/DeskLight/POWER"
  availability_topic: "tele/DeskLight/LWT"
  brightness_state_topic: "stat/BDeskLight/RESULT"
  brightness_command_topic: "cmnd/DeskLight/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Alcove Light Switch"
  state_topic: "stat/LoftAlcoveLight/POWER"
  command_topic: "cmnd/LoftAlcoveLight/POWER"
  availability_topic: "tele/LoftAlcoveLight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Half Bath Switch"
  state_topic: "stat/HalfBath/POWER"
  command_topic: "cmnd/HalfBath/POWER"
  availability_topic: "tele/HalfBath/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Hall Bath Switch"
  state_topic: "stat/HallBathLight/POWER"
  command_topic: "cmnd/HallBathLight/POWER"
  availability_topic: "tele/HallBathLight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Network Closet Light"
  state_topic: "stat/NetworkCloset/POWER"
  command_topic: "cmnd/NetworkCloset/POWER"
  availability_topic: "tele/NetworkCloset/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Porch Light"
  state_topic: "stat/PorchLight/POWER"
  command_topic: "cmnd/PorchLight/POWER"
  availability_topic: "tele/PorchLight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Garage Light"
  state_topic: "stat/garagelight/POWER"
  command_topic: "cmnd/garagelight/POWER"
  availability_topic: "tele/garagelight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Guest Room Floor Lamp"
  state_topic: "stat/GuestBedroomLightSw/POWER"
  command_topic: "cmnd/GuestBedroomLightSw/POWER"
  availability_topic: "tele/GuestBedroomLightSw/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Guest Room Nightstand Lamp"
  state_topic: "stat/GuestRoomLamp/POWER"
  command_topic: "cmnd/GuestRoomLamp/POWER"
  availability_topic: "tele/GuestRoomLamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Guest Room Bed Lamp"
  state_topic: "stat/guest_bed_light/POWER"
  command_topic: "cmnd/guest_bed_light/POWER"
  availability_topic: "tele/guest_bed_light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Loft Fan
- platform: mqtt
  name: "Loft Fan Light"
  state_topic: "stat/LoftFan/POWER1"
  # value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/LoftFan/POWER1"
  availability_topic: "tele/LoftFan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Hallway Lights
- platform: mqtt
  name: "Hallway Lights MQTT"
  state_topic: "stat/sonoffHall3Way/POWER1"
  command_topic: "cmnd/sonoffHall3Way/EVENT"
  availability_topic: "tele/sonoffHall3Way/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Kitchen Overhead Light
- platform: mqtt
  name: "Kitchen OverheadLights mqtt"
  state_topic: "stat/KitchenLights3W/POWER1"
  command_topic: "cmnd/KitchenLights3W/EVENT"
  availability_topic: "tele/KitchenLights3W/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Peninsula Light Switch"
  state_topic: "stat/peninsula_light_switch/POWER"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/peninsula_light_switch/POWER"
  availability_topic: "tele/peninsula_light_switch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Under Cabinet Lights Switch"
  state_topic: "stat/under_cabinet_lights_switch/POWER"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/under_cabinet_lights_switch/POWER"
  availability_topic: "tele/under_cabinet_lights_switch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Pier Lights"
  state_topic: "stat/pierlights/POWER"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/pierlights/POWER"
  availability_topic: "tele/pierlights/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Flood lights RGBWW
- platform: mqtt
  name: "Flood Light 1"
  command_topic: "cmnd/Flood1/POWER"
  state_topic: "tele/Flood1/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood1/LWT"
  brightness_command_topic: "cmnd/Flood1/Dimmer"
  brightness_state_topic: "tele/Flood1/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood1/CT"
  color_temp_state_topic: "tele/Flood1/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood1/Color2"
  rgb_state_topic: "tele/Flood1/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood1/Scheme"
  effect_state_topic: "tele/Flood1/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Flood Light 2"
  command_topic: "cmnd/Flood2/POWER"
  state_topic: "tele/Flood2/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood2/LWT"
  brightness_command_topic: "cmnd/Flood2/Dimmer"
  brightness_state_topic: "tele/Flood2/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood2/CT"
  color_temp_state_topic: "tele/Flood2/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood2/Color2"
  rgb_state_topic: "tele/Flood2/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood2/Scheme"
  effect_state_topic: "tele/Flood2/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Flood Light 3"
  command_topic: "cmnd/Flood3/POWER"
  state_topic: "tele/Flood3/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood3/LWT"
  brightness_command_topic: "cmnd/Flood3/Dimmer"
  brightness_state_topic: "tele/Flood3/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood3/CT"
  color_temp_state_topic: "tele/Flood3/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood3/Color2"
  rgb_state_topic: "tele/Flood3/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood3/Scheme"
  effect_state_topic: "tele/Flood3/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Pond Light"
  command_topic: "cmnd/Flood4/POWER"
  state_topic: "tele/Flood4/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood4/LWT"
  brightness_command_topic: "cmnd/Flood4/Dimmer"
  brightness_state_topic: "tele/Flood4/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood4/CT"
  color_temp_state_topic: "tele/Flood4/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood4/Color2"
  rgb_state_topic: "tele/Flood4/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood4/Scheme"
  effect_state_topic: "tele/Flood4/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Office RGBW"
  availability_topic: "tele/office_rgbw/LWT"
  command_topic: "cmnd/office_rgbw/POWER1"
  state_topic: "stat/office_rgbw/RESULT"
  state_value_template: "{{value_json.POWER}}"
  brightness_command_topic: "cmnd/office_rgbw/Dimmer"
  brightness_state_topic: "stat/office_rgbw/RESULT"
  brightness_value_template: "{{value_json.Dimmer}}"
  brightness_scale: 100
  rgb_command_topic: "cmnd/office_rgbw/Color2"
  rgb_state_topic: "tele/office_rgbw/RESULT"
    # RGB<->RGBWW conversion
  rgb_value_template: >
    {% set red = (value_json.Color.split(',')[0] | round(0)) %}
    {% set green = (value_json.Color.split(',')[1] | round(0)) %}
    {% set blue = (value_json.Color.split(',')[2] | round(0)) %}
    {% set white = (value_json.Color.split(',')[3] | round(0)) %}
    {{ green + white }},{{ red + white }},{{ blue + white }}
  rgb_command_template: >
    {% if red==green and red==blue %}
      0,0,0,{{ red }}
    {% else %}
      {{ green }},{{ red }},{{ blue  }},0
    {% endif %}
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

##########
# Switch #
##########
- platform: switch
  name: Bar Lights
  entity_id: switch.bar_lights_switch
- platform: switch
  name: Deck Flood Lights
  entity_id: switch.deck_flood_lights_switch
- platform: switch
  name: Entryway Light
  entity_id: switch.entryway_light_switch
- platform: switch
  name: Fireplace Lights
  entity_id: switch.fireplace_lights_switch
- platform: switch
  name: Garage Flood Lights
  entity_id: switch.garage_flood_lights_switch
- platform: switch
  name: Globe Lamp
  entity_id: switch.globe_lamp_switch
- platform: switch
  name: Landscaping Lights
  entity_id: switch.landscaping_lights
- platform: switch
  name: Outdoor String Lights
  entity_id: switch.outdoor_string_lights
- platform: switch
  name: Patio Flood Lights
  entity_id: switch.patio_flood_lights_switch
- platform: switch
  name: Pergola Fan
  entity_id: switch.pergola_fan
- platform: switch
  name: Reading Lamp
  entity_id: switch.reading_lamp_switch
- platform: switch
  name: Table Lamps
  entity_id: switch.table_lamps_switch
- platform: switch
  name: Workshop Light
  entity_id: switch.workshop_light_switch
###################
# Template Lights #
###################
- platform: template
  lights:
    hallway_lights:
      friendly_name: Hallway Lights
      value_template: '{{ is_state("light.hallway_lights_mqtt", "on") }}'
      turn_on:
        - condition: state
          entity_id: light.hallway_lights_mqtt
          state: 'off'
        - service: light.turn_on
          entity_id: light.hallway_lights_mqtt
      turn_off:
        - condition: state
          entity_id: light.hallway_lights_mqtt
          state: 'on'
        - service: light.turn_off
          entity_id: light.hallway_lights_mqtt
    kitchen_overhead_lights:
      friendly_name: Kitchen Overhead Lights
      value_template: '{{ is_state("light.kitchen_overheadlights_mqtt", "on") }}'
      turn_on:
        - condition: state
          entity_id: light.kitchen_overheadlights_mqtt
          state: 'off'
        - service: light.turn_on
          entity_id: light.kitchen_overheadlights_mqtt
      turn_off:
        - condition: state
          entity_id: light.kitchen_overheadlights_mqtt
          state: 'on'
        - service: light.turn_off
          entity_id: light.kitchen_overheadlights_mqtt