#####################
# Date/Time Sensors #
#####################
- platform: time_date
  display_options:
    - 'date_time_iso'
    - 'date_time_utc'

##################
# Discogs Sensor #
##################
- platform: discogs
  token: !secret discogs_token
  monitored_conditions:
    - collection

##################
# Energy Sensors #
##################
- platform: emoncms
  api_key: !secret openenergy_api
  url: https://emoncms.org
  id: 1
  unit_of_measurement: "W"
  include_only_feed_id:
    - 208205
    - 208248
    - 208210

################    
# MQTT Sensors #
################
- platform: mqtt
  name: "Workshop Temperature"
  state_topic: 'tele/AFSHT31/SENSOR'
  unit_of_measurement: '°F'
  value_template: '{{ value_json["SHT3X-0x44"]["Temperature"] }}'
  unique_id: workshop_temperature
- platform: mqtt
  name: "Workshop Humidity"
  state_topic: 'tele/AFSHT31/SENSOR'
  unit_of_measurement: '%'
  value_template: '{{ value_json["SHT3X-0x44"]["Humidity"] }}'
  unique_id: workshop_humidity
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: 'tele/BedroomTemp/SENSOR'
  unit_of_measurement: '°F'
  value_template: '{{ value_json["HTU21"]["Temperature"] }}'
  unique_id: bedroom_temperature
- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: 'tele/BedroomTemp/SENSOR'
  unit_of_measurement: '%'
  value_template: '{{ value_json["HTU21"]["Humidity"] }}'
  unique_id: bedroom_humidity
  # Roomba Sensors
- platform: mqtt
  name: "Loft Roomba Status"
  state_topic: "roomba/currentStatus"
  unique_id: loft_roomba_status
- platform: mqtt
  name: "Loft Roomba Battery"
  state_topic: "roomba/battery"
  unique_id: loft_roomba_battery
- platform: mqtt
  name: "Loft Roomba Battery Filtered"
  state_topic: "roomba/filterbattery"
  unique_id: loft_roomba_filtered_battery
- platform: mqtt
  name: "Loft Roomba Check In"
  state_topic: "checkIn/roomba"
  unique_id: loft_roomba_check_in

###################
# RESTful Sensors #
###################
- platform: rest
  resource: !secret mtb_project_url
  method: GET
  name: "Trail Status"
  value_template: 'OK'
  json_attributes:
    - "0"
    - "1"
    - "2"
- platform: rest
  resource: !secret aw_url
  method: GET
  device_class: temperature
  force_update: true
  name: "ambient_weather_feels_like_indoor"
  value_template: '{{value_json[0]["lastData"]["feelsLikein"]}}'
  scan_interval: 180

# - platform: mqtt_room
#   device_id: 2f234454cf6d4a0fadf2f4911ba9ffa6-1986-6891
#   away_timeout: 30
#   name: 'Example iBeacon'

##########################
# System Monitor Sensors #
##########################
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: disk_use_percent
      arg: /

####################
# Template Sensors #
####################
- platform: template
  sensors:
    # Front Door Lock
    front_door_lock_status: 
      friendly_name: 'Front Door Lock Status'
      value_template: "{{ state_attr('lock.front_door_lock_locked', 'lock_status') }}"
      unique_id : front_door_lock_status    
    # Harmony Remote 
    living_room_remote_current_activity:
      friendly_name: 'Living Room Remote Current Activity'
      value_template: "{{ state_attr('remote.living_room', 'current_activity') }}"    
      unique_id: living_room_remote_current_activity
    # Kitchen Door Lock
    kitchen_door_lock_status: 
      friendly_name: 'Kitchen Door Lock Status'
      value_template: "{{ state_attr('lock.kitchen_door_lock_locked', 'lock_status') }}"
      unique_id : kitchen_door_lock_status
    # Octoprint converts seconds to real time
    octoprint_time_elapsed_format:
      friendly_name: 'Printing Time Elapsed'
      value_template: >-
        {% set etime = states.sensor.octoprint_time_elapsed.state | int %}
        {% set seconds = etime % 60 %}
        {% set minutes = ((etime % 3600) / 60) | int %}
        {% set hours = ((etime % 86400) / 3600) | int %}
        {% set days = (etime / 86400) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if minutes == 1 -%}
            1 minute
          {%- else -%}
            {{ minutes }} minutes
          {%- endif -%}
        {%- endif -%}
      unique_id: octo_print_elapsed_time
    octoprint_time_remaining_format:
      friendly_name: 'Printing Time Remaining'
      value_template: >-
        {% set rtime = states.sensor.octoprint_time_remaining.state | int %}
        {% set seconds = rtime % 60 %}
        {% set minutes = ((rtime % 3600) / 60) | int %}
        {% set hours = ((rtime % 86400) / 3600) | int %}
        {% set days = (rtime / 86400) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if minutes == 1 -%}
            1 minute
          {%- else -%}
            {{ minutes }} minutes
          {%- endif -%}
        {%- endif -%}
      unique_id: octoprint_remaining_time
    # Trail Status
    fort_harrison_trail_status:
      friendly_name: "Fort Harrison Trail Status"
      value_template: '{{ states.sensor.trail_status.attributes["0"]["conditionColor"]}}'
      unique_id: fh_trail_status
    fort_harrison_last_update:
      friendly_name: "Fort Harrison Last Update"
      value_template: '{{ as_timestamp(strptime(states.sensor.trail_status.attributes["0"]["conditionDate"], "%Y-%m-%d %H:%M:%S")) | timestamp_custom("%D") }}'
      unique_id: fh_last_update
    town_run_trail_status:
      friendly_name: "Town Run Trail Status"
      value_template: '{{ states.sensor.trail_status.attributes["1"]["conditionColor"]}}'
      unique_id: tr_trail_status
    town_run_last_update:
      friendly_name: "Town Run Last Update"
      value_template: '{{ as_timestamp(strptime(states.sensor.trail_status.attributes["1"]["conditionDate"], "%Y-%m-%d %H:%M:%S")) | timestamp_custom("%D") }}'
      unique_id: tr_last_update
    flat_fork_trail_status:
      friendly_name: "Flat Fork Trail Status"
      value_template: '{{ states.sensor.trail_status.attributes["2"]["conditionColor"]}}'
      unique_id: ff_trail_status
    flat_fork_last_update:
      friendly_name: "Flat Fork Last Update"
      value_template: '{{ as_timestamp(strptime(states.sensor.trail_status.attributes["2"]["conditionDate"], "%Y-%m-%d %H:%M:%S")) | timestamp_custom("%D") }}'
      unique_id: ff_last_update
    # Workshop Door Lock
    workshop_door_lock_status: 
      friendly_name: 'Workshop Door Lock Status'
      value_template: "{{ state_attr('lock.workshop_door_lock_locked', 'lock_status') }}"
      unique_id: workshop_door_lock_status
    # Workshop Smoke Detector
    workshop_smoke_detector_status:
      value_template: >-
          {%- if is_state('sensor.workshop_smoke_detector_alarm_type', '13') %}
              Idle
          {%- elif is_state('sensor.workshop_smoke_detector_alarm_type', '1') %}
              Fire Detected
          {%- elif is_state('sensor.workshop_smoke_detector_alarm_type', '2') %}
              Carbon Monoxide Detected
          {%- elif is_state('sensor.workshop_smoke_detector_alarm_type', '12') %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: "Workshop Smoke Detector Status"
      unique_id: workshop_smoke_detector_status
    workshop_smoke_detector_battery:
      value_template: "{{ state_attr('zwave.workshop_smoke_detector', 'battery_level') }}"
      friendly_name: 'Smoke/CO Alarm Battery'
      device_class: battery
      unique_id: workshop_smoke_detector_battery_status

#####################
# Time Date Sensors #
#####################
- platform: time_date
  display_options: date_time

###################
# Weather Sensors #
###################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - icon
    - daily_summary
    - alerts
# END