#################
# MQTT Switches #
#################
# new 11/13/18 Holiday switch
- platform: mqtt
  name: "Audio Effects"
  state_topic: "holidayLights/audio/state"
  command_topic: "holidayLights/addEffects"
  payload_on: "Audio On"
  payload_off: "Audio Off"
  retain: false
- platform: mqtt
  name: "Add Glitter"
  state_topic: "holidayLights/glitter/state"
  command_topic: "holidayLights/addEffects"
  payload_on: "Glitter On"
  payload_off: "Glitter Off"
  retain: false
- platform: mqtt
  name: "Add Lightning"
  state_topic: "holidayLights/lightning/state"
  command_topic: "holidayLights/addEffects"
  payload_on: "Lightning On"
  payload_off: "Lightning Off"
  retain: false
  # Holiday Sonoff switch
- platform: mqtt
  name: "Outdoor String Lights"
  state_topic: "stat/xmaslight1/POWER"
  command_topic: "cmnd/xmaslight1/POWER"
  availability_topic: "tele/xmaslight1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  optimistic: false
# Exahust Fan
- platform: mqtt
  name: "Bedroom Exhaust Fan"
  state_topic: "stat/MB_Exhaust_Fan/POWER"
  command_topic: "cmnd/MB_Exhaust_Fan/POWER"
  availability_topic: "tele/MB_Exhaust_Fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
#IP 192.168.1.107
- platform: mqtt
  name: "zUnused Plug"
  state_topic: "stat/SonoffOutlet1_S31/POWER"
  command_topic: "cmnd/SonoffOutlet1_S31/POWER"
  availability_topic: "tele/SonoffOutlet1_S31/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  optimistic: false
  unique_id: 1921681107switch
  # Roomba Switch
- platform: mqtt
  name: "Roomba"
  command_topic: "roomba/commands"
  payload_on: "start"
  payload_off: "stop"
- platform: mqtt
  name: "Main Water Valve"
  state_topic: "stat/Main_Water_Valve/POWER"
  command_topic: "cmnd/Main_Water_Valve/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: true
  retain: false # conflicting with Tasmota retained, was causing power on following power off not previous state
- platform: mqtt
  name: "Gutter Heater 1"
  state_topic: "stat/Outdoor_Plug_Switch3/POWER1"
  command_topic: "cmnd/Outdoor_Plug_Switch3/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Gutter Heater 2"
  state_topic: "stat/Outdoor_Plug_Switch3/POWER2"
  command_topic: "cmnd/Outdoor_Plug_Switch3/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Pond Heater"
  state_topic: "stat/Outdoor_Plug_Switch3/POWER3"
  command_topic: "cmnd/Outdoor_Plug_Switch3/POWER3"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Loft Humidifier"
  state_topic: "stat/LoftHumidifier/POWER"
  command_topic: "cmnd/LoftHumidifier/POWER"
  availability_topic: "tele/LoftHumidifier/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  optimistic: false
- platform: mqtt
  name: "Landscaping Lights"
  state_topic: "stat/Outdoor2chSwitch/POWER1"
  command_topic: "cmnd/Outdoor2chSwitch/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Pergola Fan"
  state_topic: "stat/Outdoor2chSwitch/POWER2"
  command_topic: "cmnd/Outdoor2chSwitch/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true